### ISSUE TITLE
Support for non css modules

### ISSUE THREAD

**Issue by catamphetamine** [dferber90/fake-style-loader#1]
``` js
    'var content = require(' + loaderUtils.stringifyRequest(this, '!!' + remainingRequest) + ');',
    'if (typeof content === "string") return content;',
    '',
    'module.exports = content.locals || {}',
    'module.exports.source = content',
}
```

What do you think about returning the string instead of that strange `[[module.id, content, ""]]` array?

**Comment by dferber90** [comment]
It's been quite some time since I created these loaders so I'm not familiar with everything anymore. Please correct me if I'm wrong. Sorry if I'm not making any sense, I'm really out of that context right now.

What would be the purpose of supporting non-css modules? Which exports would you expect from `fake-style-loader`? If you just want the plain css, couldn't you simply use `css-loader`?

As background, I got the strange array from style-loader ([here](https://github.com/webpack/style-loader/blob/master/index.js#L16)), and I wanted `style-loader` and `fake-style-loader` to have the same exports (except for the `source` property) so I just copied it. The array is used in `style-loader` internally to manage the style tags.

**Comment by catamphetamine** [comment]
Oh, I see.
OK.
I'm not that kind of webpack guru too.
It would just make sense for `require('*.css')` to return CSS text rather than an array, I guess.
If you're familiar with this change I can make a PR.
If you're not I can copy-paste your loader and build upon it.

**Comment by dferber90** [comment]
I think your code change would have to be adapted a bit, because returning probably doesn't make sense. Instead you'd want to export `content` directly. But at that point, it's the same as leaving out `fake-style-loader` completely. I'm open to enable non-css-module support if there isn't an easier way to get the same result. I think it requires some more thought and testing, so I don't want to rush this.

I plan to spend some time on it this evening (in ~6 hours). I'll get back to you then :)

**Comment by catamphetamine** [comment]
Oh, yeah, definitely, not returning, but exporting.
OK, take your time, I'm in no rush, it's just I saw your loader today and they said that I should use it.

**Comment by dferber90** [comment]
To find out the exact behavior expected from the fake-loaders, I started working on a minimal example project which uses them, because [dferber90/webapp](https://github.com/dferber90/webapp) does so many things at once it's hard to figure out a single thing on its own). The new minimal example will show how to configure webpack with fake-loaders for development and production. Could take a bit to finish though.

I feel like I'm definitely onto something with this fake-loaders approach although it certainly is not perfect at the moment. The general idea is to provide counterparts to the regular loaders.

I don't know the complete scope of your webpack-isomorphic-tools (which was an inspiration for the fake-loaders ☺️) but I think these two approaches try to solve the same problem, although fake-loaders seem to be less configuration and more in line with webpack's _loader-for-eveything_ philosophy.

I'd welcome your input once the example is published :)

**Comment by catamphetamine** [comment]
Oh, i see)
Don't let the stars on my repo fool you, it's just a hack.
I wrote universal-webpack library and there i just dispose style loader
from the loader chain.
Folks told me i should replace style loader with your loader instead.
I guess i'll just do that. Tomorrow

**Comment by dferber90** [comment]
I just took a look at universal-web [universal-webpack](https://github.com/halt-hammerzeit/universal-webpack). It is the same approach I took in [dferber90/webapp](https://github.com/dferber90/webapp). Ah, so you want to get around [this drawback](https://github.com/halt-hammerzeit/universal-webpack#drawbacks)? The fake-loaders will let you avoid that right now 👍 

You can put your own loader in front of `fake-style-loader` which converts the array into a format you want. I think that's the way I'm going to go with the minimal example as well. It will be good to have a table showing which loaders to use where like:

| env/arch | development | production |
| --- | --- | --- |
| client | <ul><li>`*.css`: style-loader!css-loader</li><li>`*.png`: url-loader</li></ul> | <ul><li>`*.css`: style-loader!css-loader</li><li>`*.png`: url-loader</li></ul> |
| server | <ul><li>`*.css`: fake-style-loader!css-loader</li><li>`*.png`: fake-url-loader</li></ul> | <ul><li>`*.css`: fake-style-loader!css-loader</li><li>`*.png`: url-loader</li></ul> |

**This table is just an example on what I plan to build, it is not correct at the moment.**

For modules mode, we need the information in the array, so we can build up a list of all css source while avoiding duplicates (if two css-files compose from the same file, we don't need to include that file twice). An example for this is in my webapp project [in this file](https://github.com/dferber90/webapp/blob/master/modules/utils/loadStylesFromComponents.js). I'm not sure whether that de-duplication is required in regular css mode. It needs investigation.

**Comment by catamphetamine** [comment]
Oh, okay, so you're working in that direction too.

So, say, we have a `url-loader` for images.
And we have a code like:

``` css
background-image: url('...')
```

The image is then written as `fhakljsdhflkjasdhflasdjk.png` into the build folder.

Do your fake loaders provide a way to avoid writing the image to the disk while leaving all `url('...png')` and `require('...png')` calls working as expected? (i.e. returning the image URL)

Currently I just drop out `style-loader`.
I can replace it with `fake-style-loader`.
Then also the requirement for extracting all the css arises.
@sokra achieves that using `styleCollector`:
https://github.com/webpack/react-webpack-server-side-example/blob/master/server/page.js#L18
His solution would probably work for a single thread, but for a proper callback-powered page loading flow that could introduce bugs through using that global module variable to store css.

I was thinking of cloning `ExtractTextPlugin` and modifying it the way that it wouldn't remove styles from the bundle, it would instead leave the styles where they were and also accumulate a copy of all styles in the project outputting it to a file so that the server side code `<link/>` tag could include that file (in development mode).

We could just use `ExtractTextPlugin` on the client but it doesn't support HMR
https://github.com/webpack/extract-text-webpack-plugin/issues/30
So retaining `style-loader` is required on the client side, at the same time mimicking `ExtractTextPlugin` functionality.

And having that accumulated style in the `<link/>` tag the `fake-style-loader` would fit well on the server to return that `local` map for css modules and doing nothing for regular css.

**Comment by catamphetamine** [comment]
@dferber90 
Aha, I see, so you're solving this task by setting a convention for building a React Application: by requiring all CSS styles go into the `styles` property of each React component.
https://github.com/dferber90/webapp/blob/master/modules/components/Footer.js#L10
Other people tend to not liking conventions usually, everyone has his own way.
And also it adds some noise by having all that bootstrapping code (if server then ...) to the application.

**Comment by catamphetamine** [comment]
@dferber90 (`fake-style-loader` is now in my project)
https://github.com/halt-hammerzeit/universal-webpack/commit/0b83084bfc5a741899ec5e6c24a6d8427d12d2cf

**Comment by dferber90** [comment]
> Oh, okay, so you're working in that direction too.

I used to. I'm currently busy with other stuff but I'd like to sort this all out one day :)

> Do your fake loaders provide a way to avoid writing the image to the disk while leaving all url('...png') and require('...png') calls working as expected? (i.e. returning the image URL)

I think so! Would require verification though.

> Then also the requirement for extracting all the css arises.

This is not something the fake-loaders have to handle I'd say. A custom loader could collect them, or the app could do it itself like I do in webapp.

> I was thinking of cloning `ExtractTextPlugin`

I haven't looked into that plugin myself yet, so I'm not familiar with its internals.

> Other people tend to not liking conventions usually, everyone has his own way.

It's totally up to the developer how he handles it. This is just my version. The `fake-loaders` are small building blocks which other stuffy can rely upon.

> And also it adds some noise by having all that bootstrapping code (if server then ...) to the application.

This could be done automatically using a babel-plugin or a decorator (which would be implemented as a noop on the client) or something like that :)

---

Your universal-webpack project basically adapts the webpack configuration for all different environments, right? So far I went with adding 4 different configurations (`dev.client.js, dev.server.js, prod.client.js, prod.server.js`) in my projects. I found it very relaxing to use almost no logic in configs and rather repeat almost every setting across the 4 configs. This makes writing them easier because there's less to grasp. Once we have figured out how exactly they need to be configured it's easy to write a short how-to and a boilerplate. This keeps all the webpack power in the hands of the project. But I also see the value of universal-webpack.

**Comment by dferber90** [comment]
I'm only inlining the CSS modules used by the rendered components, while leaving the other stuff out. 
This is described in detail here https://github.com/dferber90/webapp/blob/master/knowhow/css-modules.md, although that is specific to webapp. This was an experiment, not something I'd consider _ready for production_.

**Comment by catamphetamine** [comment]
Ok.
Thanks for the explanation, I've reconsidered some of my thoughts during this whole discussion.

**Comment by catamphetamine** [comment]
(oh, I forgot to close this issue)
